name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # Ou qualquer outra branch que você usa para deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
        
    - name: Criar hugo.toml dinamicamente
      run: |
        echo '[services]' > hugo.toml
        echo '[services.googleAnalytics]' >> hugo.toml
        echo "id = '${{ secrets.GOOGLE_ANALYTICS_ID }}'" >> hugo.toml

    - name: Build Hugo site
      env:
        GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}  # Passa o segredo para o build
      run: hugo

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public