name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # Ou qualquer outra branch que você usa para o deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2

    - name: Build Hugo site
      env:
        GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}  # Aqui você usa o GitHub Secret
      run: hugo

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
    - name: Replace GOOGLE_ANALYTICS_ID in hugo.toml
      run: |
        sed -i "s/GOOGLE_ANALYTICS_PLACEHOLDER/${{ secrets.GOOGLE_ANALYTICS_ID }}/g" hugo.toml