name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # Ou qualquer outra branch que você usa para o deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

      # 🔥 Etapa de debug para inspecionar variáveis de ambiente
    - name: Debug - Verificar variáveis de ambiente
      run: printenv

    - name: Set up environment variables
      run: echo "GOOGLE_ANALYTICS_ID=${{ secrets.GOOGLE_ANALYTICS_ID }}" >> $GITHUB_ENV

    - name: Build site with environment variable
      run: hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
